# 路径：.github/workflows/html.yml

name: Convert PDF → HTML & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'KG2QA.pdf'                          # 指定要监控的 PDF 文件
      - '.github/workflows/html.yml'         # workflow 自身改动也要触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 签出仓库代码（带完整历史）
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. 安装 pdf2htmlEX
      - name: Install pdf2htmlEX
        run: |
          sudo apt-get update
          sudo apt-get install -y pdf2htmlEX

      # 3. 转换 KG2QA.pdf → docs/KG2QA.html
      - name: Convert KG2QA.pdf to HTML
        run: |
          mkdir -p docs
          pdf2htmlEX \
            --dest-dir docs \
            --dest-file KG2QA.html \
            KG2QA.pdf

      # 4. 提交并推送生成的 HTML 到 docs/（用于 Pages）
      - name: Commit HTML to docs/
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: convert KG2QA.pdf to HTML"
          push: true
