name: Convert PDF → HTML & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'KG2QA.pdf'                        
      - '.github/workflows/html.yml'       

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pdf2htmlEX
        run: |
          sudo apt-get update
          sudo apt-get install -y pdf2htmlEX

      - name: Convert KG2QA.pdf to HTML
        run: |
          mkdir -p docs
          pdf2htmlEX \
            --dest-dir docs \
            --dest-file KG2QA.html \
            KG2QA.pdf

      - name: Commit HTML to docs/
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: convert KG2QA.pdf to HTML"
          push: true
